services:
  patient-db:
    image: mysql:8
    container_name: patient-db
    mem_limit: 256m
    environment:
      MYSQL_DATABASE: patient_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    command: --innodb-buffer-pool-size=64M --innodb-log-file-size=32M

  vitals-db:
    image: mysql:8
    container_name: vitals-db
    mem_limit: 256m
    environment:
      MYSQL_DATABASE: vitals_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    command: --innodb-buffer-pool-size=64M --innodb-log-file-size=32M

  notification-db:
    image: mysql:8
    container_name: notification-db
    mem_limit: 256m
    environment:
      MYSQL_DATABASE: notification_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3309:3306"
    command: --innodb-buffer-pool-size=64M --innodb-log-file-size=32M

  appointment-db:
    image: mysql:8
    container_name: appointment-db
    mem_limit: 256m
    environment:
      MYSQL_DATABASE: appointment_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3310:3306"
    command: --innodb-buffer-pool-size=64M --innodb-log-file-size=32M

  patient-service:
    build: ./patient-service
    container_name: patient-service
    mem_limit: 256m
    ports:
      - "8081:8081"
    depends_on:
      - patient-db
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx128m -Xms64m"

  vitals-service:
    build: ./vitals-service
    container_name: vitals-service
    mem_limit: 256m
    ports:
      - "8084:8084"
    depends_on:
      - vitals-db
      - patient-service
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx128m -Xms64m"

  notification-service:
    build: ./notification-service
    container_name: notification-service
    mem_limit: 256m
    ports:
      - "8085:8085"
    depends_on:
      - notification-db
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx128m -Xms64m"

  appointment-service:
    build: ./appointment-service
    container_name: appointment-service
    mem_limit: 256m
    ports:
      - "8082:8082"
    depends_on:
      - appointment-db
    restart: on-failure
    environment:
      JAVA_TOOL_OPTIONS: "-Xmx128m -Xms64m"